# Generated by Django 5.1.6 on 2025-03-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_edition', models.CharField(blank=True, max_length=50, null=True)),
                ('book_condition', models.CharField(choices=[('Fresh', 'Fresh'), ('Scribbled', 'Scribbled'), ('Worn', 'Worn')], max_length=50)),
                ('course_identifier', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
