# Generated by Django 5.1.6 on 2025-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookexchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('worn', 'Worn')], max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TradeBook',
        ),
    ]
